package com.Jeka8833.LinkBot.kpi;

public class SavedDB {

    // CSV to Json
    // https://www.convertcsv.com/csv-to-json.htm

    public static final String data = """
            [
             {
               "lesson_id": 1,
               "day_number": 1,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Наноструктури в оптоелектроніці",
               "teacher_name": "Свєчніков Георгій Сергійович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "08:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 2,
               "day_number": 1,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Наноструктури в оптоелектроніці",
               "teacher_name": "Свєчніков Георгій Сергійович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 3,
               "day_number": 1,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Конструювання електронних приладів і пристроїв",
               "teacher_name": "Мачулянський Олександр Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 4,
               "day_number": 1,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Конструювання електронних приладів і пристроїв",
               "teacher_name": "Мачулянський Олександр Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 5,
               "day_number": 1,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Іноземна мова професійного спрямування-2",
               "teacher_name": "Ситайло Наталія Миколаївна",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 6,
               "day_number": 2,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Методи дослідження матеріалів мікро- та наносистемної техніки",
               "teacher_name": "Малюта Сергій Васильович",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "08:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 7,
               "day_number": 2,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Електроніка надвисоких частот",
               "teacher_name": "Малюта Сергій Васильович",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 8,
               "day_number": 2,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Електроніка надвисоких частот",
               "teacher_name": "Татарчук Дмитро Дмитрович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 9,
               "day_number": 2,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Електроніка надвисоких частот",
               "teacher_name": "Татарчук Дмитро Дмитрович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 11,
               "day_number": 3,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Конструювання електронних приладів і пристроїв",
               "teacher_name": "Мачулянський Олександр Вікторович",
               "lesson_type": "Лаб",
               "lesson_class": "-",
               "time_start": "08:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 12,
               "day_number": 3,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Оптоелектроніка",
               "teacher_name": "Воронько А. О.",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 13,
               "day_number": 3,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Оптоелектроніка",
               "teacher_name": "Воронько А. О.",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 14,
               "day_number": 3,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Методи дослідження матеріалів мікро- та наносистемної техніки",
               "teacher_name": "Верцанова Олена Вікторівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 15,
               "day_number": 3,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Методи дослідження матеріалів мікро- та наносистемної техніки",
               "teacher_name": "Верцанова Олена Вікторівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 16,
               "day_number": 4,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Оптоелектроніка",
               "teacher_name": "Воронько А. О.",
               "lesson_type": "Лаб",
               "lesson_class": "-",
               "time_start": "08:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 17,
               "day_number": 4,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Наноструктури в оптоелектроніці",
               "teacher_name": "Воронько А. О.",
               "lesson_type": "Лаб",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 18,
               "day_number": 4,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Програмовані логічні інтегральні схеми",
               "teacher_name": "Діденко Юрій Вікторович",
               "lesson_type": "Лаб",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 19,
               "day_number": 4,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Мікрохвильова техніка",
               "teacher_name": "Тимофєєв Володимир Іванович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 20,
               "day_number": 4,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Мікрохвильова техніка",
               "teacher_name": "Тимофєєв Володимир Іванович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 21,
               "day_number": 5,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Програмовані логічні інтегральні схеми",
               "teacher_name": "Діденко Юрій Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "08:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 22,
               "day_number": 5,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Програмовані логічні інтегральні схеми",
               "teacher_name": "Діденко Юрій Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 23,
               "day_number": 5,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Біомедичні сенсори",
               "teacher_name": "Коваль Вікторія Михайлівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 24,
               "day_number": 5,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Біомедичні сенсори",
               "teacher_name": "Коваль Вікторія Михайлівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 25,
               "day_number": 5,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Біомедичні сенсори",
               "teacher_name": "Коваль Вікторія Михайлівна",
               "lesson_type": "Лаб",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 26,
               "day_number": 1,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Наноструктури в оптоелектроніці",
               "teacher_name": "Свєчніков Георгій Сергійович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "08:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 27,
               "day_number": 1,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Наноструктури в оптоелектроніці",
               "teacher_name": "Свєчніков Георгій Сергійович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 28,
               "day_number": 1,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Конструювання електронних приладів і пристроїв",
               "teacher_name": "Мачулянський Олександр Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 29,
               "day_number": 1,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Конструювання електронних приладів і пристроїв",
               "teacher_name": "Мачулянський Олександр Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 30,
               "day_number": 1,
               "lesson_number": 5,
               "lesson_week": 2,
               "lesson_name": "Іноземна мова професійного спрямування-2",
               "teacher_name": "Ситайло Наталія Миколаївна",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 31,
               "day_number": 2,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Методи дослідження матеріалів мікро- та наносистемної техніки",
               "teacher_name": "Малюта Сергій Васильович",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "08:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 32,
               "day_number": 2,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Електроніка надвисоких частот",
               "teacher_name": "Малюта Сергій Васильович",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 33,
               "day_number": 2,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Електроніка надвисоких частот",
               "teacher_name": "Татарчук Дмитро Дмитрович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 34,
               "day_number": 2,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Електроніка надвисоких частот",
               "teacher_name": "Татарчук Дмитро Дмитрович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 36,
               "day_number": 3,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Конструювання електронних приладів і пристроїв",
               "teacher_name": "Мачулянський Олександр Вікторович",
               "lesson_type": "Лаб",
               "lesson_class": "-",
               "time_start": "08:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 37,
               "day_number": 3,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Оптоелектроніка",
               "teacher_name": "Воронько А. О.",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 38,
               "day_number": 3,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Оптоелектроніка",
               "teacher_name": "Воронько А. О.",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 39,
               "day_number": 3,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Методи дослідження матеріалів мікро- та наносистемної техніки",
               "teacher_name": "Верцанова Олена Вікторівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 40,
               "day_number": 3,
               "lesson_number": 5,
               "lesson_week": 2,
               "lesson_name": "Методи дослідження матеріалів мікро- та наносистемної техніки",
               "teacher_name": "Верцанова Олена Вікторівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 41,
               "day_number": 4,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Оптоелектроніка",
               "teacher_name": "Воронько А. О.",
               "lesson_type": "Лаб",
               "lesson_class": "-",
               "time_start": "08:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 42,
               "day_number": 4,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Наноструктури в оптоелектроніці",
               "teacher_name": "Воронько А. О.",
               "lesson_type": "Лаб",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 43,
               "day_number": 4,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Програмовані логічні інтегральні схеми",
               "teacher_name": "Діденко Юрій Вікторович",
               "lesson_type": "Лаб",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 44,
               "day_number": 4,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Мікрохвильова техніка",
               "teacher_name": "Тимофєєв Володимир Іванович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 45,
               "day_number": 4,
               "lesson_number": 5,
               "lesson_week": 2,
               "lesson_name": "Мікрохвильова техніка",
               "teacher_name": "Тимофєєв Володимир Іванович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 46,
               "day_number": 5,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Програмовані логічні інтегральні схеми",
               "teacher_name": "Діденко Юрій Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "08:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 47,
               "day_number": 5,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Програмовані логічні інтегральні схеми",
               "teacher_name": "Діденко Юрій Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 48,
               "day_number": 5,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Біомедичні сенсори",
               "teacher_name": "Коваль Вікторія Михайлівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 49,
               "day_number": 5,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Біомедичні сенсори",
               "teacher_name": "Коваль Вікторія Михайлівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 50,
               "day_number": 5,
               "lesson_number": 5,
               "lesson_week": 2,
               "lesson_name": "Біомедичні сенсори",
               "teacher_name": "Коваль Вікторія Михайлівна",
               "lesson_type": "Лаб",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             }
            ]""";
}