package com.Jeka8833.LinkBot.kpi;

public class SavedDB {

    // CSV to Json
    // https://www.convertcsv.com/csv-to-json.htm

    public static final String data = """
             [
             {
               "lesson_id": 1,
               "day_number": 1,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Інформаційні технології проектування у мікро- і наносистемах",
               "teacher_name": "Казміренко Віктор Анатолійович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 2,
               "day_number": 1,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Схемотехніка - 2. Цифрова схемотехніка",
               "teacher_name": "Казміренко Віктор Анатолійович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 3,
               "day_number": 1,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Схемотехніка - 2. Цифрова схемотехніка",
               "teacher_name": "Казміренко Віктор Анатолійович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 4,
               "day_number": 1,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Основи сенсорної електроніки",
               "teacher_name": "Коваль Вікторія Михайлівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 5,
               "day_number": 1,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Сенсорні матеріали та технології",
               "teacher_name": "Коваль Вікторія Михайлівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 6,
               "day_number": 2,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Економіка і організація виробництва",
               "teacher_name": "Шостак Інна Володимирівна",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 7,
               "day_number": 2,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Мікроконтролери",
               "teacher_name": "Татарчук Дмитро Дмитрович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 8,
               "day_number": 2,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Функціональна електроніка",
               "teacher_name": "Обухова Тетяна Юріївна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 9,
               "day_number": 2,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Функціональні пристрої для обробки інформації",
               "teacher_name": "Обухова Тетяна Юріївна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 10,
               "day_number": 2,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Економіка і організація виробництва",
               "teacher_name": "Марченко Валентина Миколаївна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 11,
               "day_number": 3,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Основи сенсорної електроніки",
               "teacher_name": "Коваль Вікторія Михайлівна",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 12,
               "day_number": 3,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Іноземна мова професійного спрямування-2",
               "teacher_name": "Ситайло Наталія Миколаївна",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 13,
               "day_number": 3,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Функціональні пристрої для обробки інформації",
               "teacher_name": "Малюта С.",
               "lesson_type": "Лаб",
               "lesson_class": "105-02",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": false,
               "choice": true
             },
             {
               "lesson_id": 14,
               "day_number": 3,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Функціональна електроніка",
               "teacher_name": "Малюта С.",
               "lesson_type": "Лаб",
               "lesson_class": "105-02",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": false,
               "choice": true
             },
             {
               "lesson_id": 15,
               "day_number": 4,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Інформаційні технології проектування у мікро- і наносистемах",
               "teacher_name": "Казміренко Віктор Анатолійович, Голубєва Ірина Петрівна",
               "lesson_type": "Лаб",
               "lesson_class": "-",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 16,
               "day_number": 4,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Охорона праці та цивільний захист",
               "teacher_name": "Полукаров Олексій Ігорович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 17,
               "day_number": 4,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Охорона праці та цивільний захист",
               "teacher_name": "Пятова Анжела Вячеславівна, Ільчук Оксана Степанівна",
               "lesson_type": "Прак, Лаб",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 18,
               "day_number": 5,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Схемотехніка - 2. Цифрова схемотехніка",
               "teacher_name": "Порєва Ганна Сергіївна",
               "lesson_type": "Лаб",
               "lesson_class": "413-12",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": false,
               "choice": false
             },
             {
               "lesson_id": 19,
               "day_number": 1,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Інформаційні технології проектування у мікро- і наносистемах",
               "teacher_name": "Казміренко Віктор Анатолійович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 20,
               "day_number": 1,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Схемотехніка - 2. Цифрова схемотехніка",
               "teacher_name": "Казміренко Віктор Анатолійович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 21,
               "day_number": 1,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Основи сенсорної електроніки",
               "teacher_name": "Коваль Вікторія Михайлівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 22,
               "day_number": 1,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Сенсорні матеріали та технології",
               "teacher_name": "Коваль Вікторія Михайлівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 23,
               "day_number": 2,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Економіка і організація виробництва",
               "teacher_name": "Шостак Інна Володимирівна",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 24,
               "day_number": 2,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Мікроконтролери",
               "teacher_name": "Татарчук Дмитро Дмитрович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 25,
               "day_number": 2,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Функціональна електроніка",
               "teacher_name": "Обухова Тетяна Юріївна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 26,
               "day_number": 2,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Функціональні пристрої для обробки інформації",
               "teacher_name": "Обухова Тетяна Юріївна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 27,
               "day_number": 2,
               "lesson_number": 5,
               "lesson_week": 2,
               "lesson_name": "Економіка і організація виробництва",
               "teacher_name": "Марченко Валентина Миколаївна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 28,
               "day_number": 3,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Сенсорні матеріали та технології",
               "teacher_name": "Коваль Вікторія Михайлівна",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 29,
               "day_number": 3,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Іноземна мова професійного спрямування-2",
               "teacher_name": "Ситайло Наталія Миколаївна",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 30,
               "day_number": 3,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Мікроконтролери",
               "teacher_name": "Татарчук Дмитро Дмитрович",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 31,
               "day_number": 4,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Схемотехніка - 2. Цифрова схемотехніка",
               "teacher_name": "Порєва Ганна Сергіївна",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 32,
               "day_number": 4,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Охорона праці та цивільний захист",
               "teacher_name": "Полукаров Олексій Ігорович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 33,
               "day_number": 4,
               "lesson_number": 5,
               "lesson_week": 2,
               "lesson_name": "Охорона праці та цивільний захист",
               "teacher_name": "Пятова Анжела Вячеславівна, Ільчук Оксана Степанівна",
               "lesson_type": "Прак, Лаб",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 34,
               "day_number": 5,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Схемотехніка - 2. Цифрова схемотехніка",
               "teacher_name": "Порєва Ганна Сергіївна",
               "lesson_type": "Лаб",
               "lesson_class": "413-12",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": false,
               "choice": false
             }
            ]""";
}