package com.Jeka8833.LinkBot.kpi;

public class SavedBD {

    // CSV to Json
    // https://www.convertcsv.com/csv-to-json.htm

    public static final String data = """
            [
             {
               "lesson_id": 2,
               "day_number": 1,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Електродинаміка",
               "teacher_name": "Савін Костянтин Георгійович, Саурова Тетяна Асадовна",
               "lesson_type": "Прак",
               "lesson_class": "409-12",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 3,
               "day_number": 1,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Наноелектроніка",
               "teacher_name": "Воронько Андрій О.",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 4,
               "day_number": 1,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Теорія сигналів та систем",
               "teacher_name": "Карплюк Євгеній Сергійович",
               "lesson_type": "Лаб",
               "lesson_class": "427-12",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 5,
               "day_number": 2,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Технологія інтегральних мікросхем",
               "teacher_name": "Воронько Андрій О.",
               "lesson_type": "Прак",
               "lesson_class": "138-12",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 6,
               "day_number": 2,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Мікромеханіка",
               "teacher_name": "Лупина Борис Іванович",
               "lesson_type": "Прак",
               "lesson_class": "134-12",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 7,
               "day_number": 2,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Іноземна мова професійного спрямування. Частина 1",
               "teacher_name": "Гордієнко Наталія Миколаївна",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 8,
               "day_number": 3,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Теорія сигналів та систем",
               "teacher_name": "Попов Антон Олександрович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 9,
               "day_number": 3,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Теорія сигналів та систем",
               "teacher_name": "Іванько Катерина Олегівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 10,
               "day_number": 3,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Наноелектроніка",
               "teacher_name": "Вербицький Володимир Григорович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 11,
               "day_number": 3,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Наноелектроніка",
               "teacher_name": "Вербицький Володимир Григорович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 12,
               "day_number": 3,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Надійність електронної апаратури",
               "teacher_name": "Королевич Любомир Миколайович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 13,
               "day_number": 3,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Технологія інтегральних мікросхем",
               "teacher_name": "Мачулянський Олександр Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 14,
               "day_number": 4,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Електродинаміка",
               "teacher_name": "Савін Костянтин Георгійович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 15,
               "day_number": 4,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Електродинаміка",
               "teacher_name": "Савін Костянтин Георгійович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 16,
               "day_number": 4,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Технологічні основи електроніки",
               "teacher_name": "Мачулянський Олександр Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 17,
               "day_number": 4,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Мікроелектроніка",
               "teacher_name": "Мачулянський Олександр Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 18,
               "day_number": 4,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Мікромеханіка",
               "teacher_name": "Лупина Борис Іванович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 19,
               "day_number": 1,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Теорія сигналів та систем",
               "teacher_name": "Карплюк Євгеній Сергійович",
               "lesson_type": "Прак",
               "lesson_class": "409-12",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 20,
               "day_number": 1,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Наноелектроніка",
               "teacher_name": "Воронько Андрій О.",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 21,
               "day_number": 1,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Технологічні основи електроніки",
               "teacher_name": "Мачулянський Олександр Вікторович",
               "lesson_type": "Прак",
               "lesson_class": "134-12",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 22,
               "day_number": 2,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Надійність електронної апаратури",
               "teacher_name": "Королевич Любомир Миколайович",
               "lesson_type": "Прак",
               "lesson_class": "138-12",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 23,
               "day_number": 2,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Мікроелектроніка",
               "teacher_name": "Королевич Любомир Миколайович",
               "lesson_type": "Прак",
               "lesson_class": "134-12",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 24,
               "day_number": 2,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Іноземна мова професійного спрямування. Частина 1",
               "teacher_name": "Гордієнко Наталія Миколаївна",
               "lesson_type": "Прак",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 25,
               "day_number": 3,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Теорія сигналів та систем",
               "teacher_name": "Попов Антон Олександрович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 26,
               "day_number": 3,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Теорія сигналів та систем",
               "teacher_name": "Іванько Катерина Олегівна",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 27,
               "day_number": 3,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Наноелектроніка",
               "teacher_name": "Вербицький Володимир Григорович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 28,
               "day_number": 3,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Надійність електронної апаратури",
               "teacher_name": "Королевич Любомир Миколайович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 29,
               "day_number": 3,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Технологія інтегральних мікросхем",
               "teacher_name": "Мачулянський Олександр Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 30,
               "day_number": 4,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Електродинаміка",
               "teacher_name": "Савін Костянтин Георгійович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 31,
               "day_number": 4,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Технологічні основи електроніки",
               "teacher_name": "Мачулянський Олександр Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 32,
               "day_number": 4,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Мікроелектроніка",
               "teacher_name": "Мачулянський Олександр Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 33,
               "day_number": 4,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Мікромеханіка",
               "teacher_name": "Лупина Борис Іванович",
               "lesson_type": "Лек",
               "lesson_class": "-",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             }
            ]
            """;
}