package com.Jeka8833.LinkBot.kpi;

public class SavedDB {

    // CSV to Json
    // https://www.convertcsv.com/csv-to-json.htm

    public static final String data = """
            [
             {
               "lesson_id": 2,
               "day_number": 1,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Об'єктно-орієнтоване програмування",
               "teacher_name": "Малюта С.",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 3,
               "day_number": 1,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Технологічні основи наноелектроніки",
               "teacher_name": "Орлов Анатолій Тимофійович",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 4,
               "day_number": 1,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Технологія наноматеріалів та наностуктур",
               "teacher_name": "Воронько Андрій О.",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 41,
               "day_number": 1,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Сучасні напівпровідникові матеріали",
               "teacher_name": "Осінов С. М.",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 6,
               "day_number": 2,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Схемотехніка. Частина 1. Аналогова схемотехніка",
               "teacher_name": "Карплюк Євгеній Сергійович, Порєва Ганна Сергіївна",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 7,
               "day_number": 2,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Підприємницьке право",
               "teacher_name": "Новошицька Валерія Ігорівна",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 8,
               "day_number": 2,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Інтелектуальні інформаційні системи",
               "teacher_name": "Заворотний Віктор Федорович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 9,
               "day_number": 2,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Функціональні діелектрики в електроніці",
               "teacher_name": "Поплавко Юрій Михайлович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 10,
               "day_number": 2,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Моделювання в електроніці",
               "teacher_name": "Верцанова Олена Вікторівна",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 11,
               "day_number": 3,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Сучасні напівпровідникові матеріали",
               "teacher_name": "Обухова Тетяна Юріївна",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 12,
               "day_number": 3,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Структури даних",
               "teacher_name": "Татарчук Дмитро Дмитрович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 13,
               "day_number": 3,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Цифрова обробка сигналів",
               "teacher_name": "Заворотний Віктор Федорович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 14,
               "day_number": 3,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Об'єктно-орієнтоване програмування",
               "teacher_name": "Татарчук Дмитро Дмитрович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 15,
               "day_number": 3,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Основи мікро- та наносистемної техніки",
               "teacher_name": "Шевлякова Г. В.",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 16,
               "day_number": 4,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Іноземна мова професійного спрямування. Частина 1",
               "teacher_name": "Ситайло Наталія Миколаївна",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 17,
               "day_number": 4,
               "lesson_number": 2,
               "lesson_week": 1,
               "lesson_name": "Основи мікро- та наносистемної техніки",
               "teacher_name": "Діденко Юрій Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 18,
               "day_number": 4,
               "lesson_number": 3,
               "lesson_week": 1,
               "lesson_name": "Інтелектуальні інформаційні системи",
               "teacher_name": "Заворотний Віктор Федорович",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 19,
               "day_number": 4,
               "lesson_number": 4,
               "lesson_week": 1,
               "lesson_name": "Схемотехніка. Частина 1. Аналогова схемотехніка",
               "teacher_name": "Савін Костянтин Георгійович, Коваленко Олександр Сергійович",
               "lesson_type": "Лаб",
               "lesson_class": "",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 20,
               "day_number": 4,
               "lesson_number": 5,
               "lesson_week": 1,
               "lesson_name": "Підприємницьке право",
               "teacher_name": "Новошицька Валерія Ігорівна",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 42,
               "day_number": 6,
               "lesson_number": 1,
               "lesson_week": 1,
               "lesson_name": "Технологія наноматеріалів та наностуктур",
               "teacher_name": "Вербицький Володимир Григорович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 23,
               "day_number": 1,
               "lesson_number": 5,
               "lesson_week": 2,
               "lesson_name": "Структури даних",
               "teacher_name": "Шевлякова Г. В.",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 24,
               "day_number": 1,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Функціональні діелектрики в електроніці",
               "teacher_name": "Поплавко Юрій Михайлович",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 44,
               "day_number": 1,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Схемотехніка. Частина 1. Аналогова схемотехніка",
               "teacher_name": "Голубєва Ірина Петрівна",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 45,
               "day_number": 1,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Схемотехніка. Частина 1. Аналогова схемотехніка",
               "teacher_name": "Голубєва Ірина Петрівна",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 28,
               "day_number": 2,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Схемотехніка. Частина 1. Аналогова схемотехніка",
               "teacher_name": "Карплюк Євгеній Сергійович, Порєва Ганна Сергіївна",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 29,
               "day_number": 2,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Інтелектуальні інформаційні системи",
               "teacher_name": "Заворотний Віктор Федорович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 30,
               "day_number": 2,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Функціональні діелектрики в електроніці",
               "teacher_name": "Поплавко Юрій Михайлович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 31,
               "day_number": 2,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Моделювання в електроніці",
               "teacher_name": "Верцанова Олена Вікторівна",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 47,
               "day_number": 2,
               "lesson_number": 5,
               "lesson_week": 2,
               "lesson_name": "Моделювання в електроніці",
               "teacher_name": "Верцанова Олена Вікторівна",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 32,
               "day_number": 3,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Сучасні напівпровідникові матеріали",
               "teacher_name": "Обухова Тетяна Юріївна",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 33,
               "day_number": 3,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Структури даних",
               "teacher_name": "Татарчук Дмитро Дмитрович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 34,
               "day_number": 3,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Цифрова обробка сигналів",
               "teacher_name": "Заворотний Віктор Федорович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 35,
               "day_number": 3,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Об'єктно-орієнтоване програмування",
               "teacher_name": "Татарчук Дмитро Дмитрович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 51,
               "day_number": 3,
               "lesson_number": 5,
               "lesson_week": 2,
               "lesson_name": "Цифрова обробка сигналів",
               "teacher_name": "Заворотний Віктор Федорович",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 36,
               "day_number": 4,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Іноземна мова професійного спрямування. Частина 1",
               "teacher_name": "Ситайло Наталія Миколаївна",
               "lesson_type": "Прак",
               "lesson_class": "",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 37,
               "day_number": 4,
               "lesson_number": 2,
               "lesson_week": 2,
               "lesson_name": "Основи мікро- та наносистемної техніки",
               "teacher_name": "Діденко Юрій Вікторович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "10:25:00",
               "time_end": "12:00:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 38,
               "day_number": 4,
               "lesson_number": 3,
               "lesson_week": 2,
               "lesson_name": "Схемотехніка. Частина 1. Аналогова схемотехніка",
               "teacher_name": "Савін Костянтин Георгійович, Коваленко Олександр Сергійович",
               "lesson_type": "Лаб",
               "lesson_class": "",
               "time_start": "12:20:00",
               "time_end": "13:55:00",
               "online": true,
               "choice": false
             },
             {
               "lesson_id": 48,
               "day_number": 4,
               "lesson_number": 4,
               "lesson_week": 2,
               "lesson_name": "Технологічні основи наноелектроніки",
               "teacher_name": "Орлов Анатолій Тимофійович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "14:15:00",
               "time_end": "15:50:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 49,
               "day_number": 4,
               "lesson_number": 5,
               "lesson_week": 2,
               "lesson_name": "Технологічні основи наноелектроніки",
               "teacher_name": "Орлов Анатолій Тимофійович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "16:10:00",
               "time_end": "17:45:00",
               "online": true,
               "choice": true
             },
             {
               "lesson_id": 50,
               "day_number": 6,
               "lesson_number": 1,
               "lesson_week": 2,
               "lesson_name": "Технологія наноматеріалів та наностуктур",
               "teacher_name": "Вербицький Володимир Григорович",
               "lesson_type": "Лек",
               "lesson_class": "",
               "time_start": "8:30:00",
               "time_end": "10:05:00",
               "online": true,
               "choice": true
             }
            ]""";
}